### ISSUE TITLE
Setting up a scheduler for command execution (build tool, dependencies)

### ISSUE THREAD

**Issue by IngwiePhoenix** [tillenius/superglue#1]
Hey there!

I am working on a concept for my own build tool and currently I am kind of window-shopping for libraries to do the things that I don't know how to do myself. Frankly, due to my visual impairment, whenever I heared the word "graph" back in school, I went into hiding relatively fast. Thus, concepts like topological graphs and the like were never taught to me - let alone, I can't usually "read" the formatted (as image) graphs either.

What I need to do is be able to set up a task scheduler to run through a set of steps. Each step consists of an input file, an estimated output filename (which is used for subsequent steps as input) and possibly other dependencies. It also contains a callback and other information. The callback is simply the business logic of each step that takes the given parameters and constructs a command to be executed. Simplified, this would be:

```c++
int run(string input, string output, Context *ctx) {
  // ...
 return shell_execute(command);
}
```

task | input | output | deps
--|-------|---------|------
1 | foo.c | foo.o | foo.c
2 | bar.c | bar.o | bar.c
3 | lib.c | lib.o | lib.c
4 | lib.o | libmylib.a | lib.o
5 | foo.o bar.o libmylib.a | app.exe | foo.o bar.o libmylib.a

How would I represent this type of execution in Superglue, and how can I log status reports of this? I.e.: In an interval of N ms, print `N of 5 tasks completed`.

Kind regards,
Ingwie

**Comment by tillenius** [comment]
Hello! Thanks for your interest in SuperGlue. :)

I put together a small example here:
https://gist.github.com/tillenius/4fba08b2c8a9e15711e37e0a3d0b5de0
that hopefully answers most questions. If something is still unclear, I'd be happy to answer questions about it.

**Comment by IngwiePhoenix** [comment]
Yes, this helps a whole lot! Decided to comment there - since this isn't exactly an issue :)

Thank you very much!
